export enum Env {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  MONGO_CONNECTION_STRING = 'MONGO_CONNECTION_STRING',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',

  ADMIN_EMAIL = 'ADMIN_EMAIL',
  ADMIN_PASSWORD = 'ADMIN_PASSWORD',

  CLOUDFRONT_URL = 'CLOUDFRONT_URL',
  AWS_S3_BUCKET_REGION = 'AWS_S3_BUCKET_REGION',
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',
  AWS_S3_BUCKET_ACCESS_KEY = 'AWS_S3_BUCKET_ACCESS_KEY',
  AWS_S3_BUCKET_SECRET_KEY = 'AWS_S3_BUCKET_SECRET_KEY',

  EMAIL_PORT = 'EMAIL_PORT',
  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_USERNAME = 'EMAIL_USERNAME',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',

  JWT_SECRET = 'JWT_SECRET',
  JWT_ACCESS_TOKEN_EXPIRES_IN = 'JWT_ACCESS_TOKEN_EXPIRES_IN',
  JWT_REFRESH_TOKEN_EXPIRES_IN = 'JWT_REFRESH_TOKEN_EXPIRES_IN',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  FRONT_END_ORIGIN = 'FRONT_END_ORIGIN',
}

export enum Tokens {
  REFRESH_TOKEN = 'refresh_token',
  ACCESS_TOKEN = 'access_token',
}
